# Copyright (c) 2024 TouchNetix
#
# This file is part of axutils and is released under the MIT License:
# See the LICENSE file in the root directory of this project or http://opensource.org/licenses/MIT.

SUCCESS = 0
ERROR_ARG_SYNTAX_ERROR = 2
ERROR_AXIOM_IN_BOOTLOADER = 3

ERROR_CFG_FILE_NOT_COMPATIBLE = 4
ERROR_CFG_FILE_MISMATCH = 5

ERROR_INVALID_OR_NO_FILE_SPECIFIED = 6
ERROR_FAILED_TO_ENTER_BOOTLOADER = 7
ERROR_AXFW_NOT_VALID = 8
ERROR_AXFW_NOT_COMPATIBLE_WITH_DEVICE = 9
INFO_FIRMWARE_LOAD_NOT_REQUIRED = 10
ERROR_AXFW_FIRMWARE_VARIANT_DIFFERENT = 11
ERROR_FIRMWARE_CRC_FAILED = 12
